version: '3.8'

services:
  # Microsoft SQL Server
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sme-dashboard-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - sme-network

  # Redis
  redis:
    image: redis:7-alpine
    container_name: sme-dashboard-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - sme-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sme-dashboard-backend
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_HOST=mssql
      - DB_PORT=1433
      - DB_NAME=sme_dashboard
      - DB_USER=sa
      - DB_PASSWORD=YourStrong@Passw0rd
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=your_super_secret_jwt_key_here
      - JWT_REFRESH_SECRET=your_refresh_secret_key_here
    ports:
      - "5000:5000"
    depends_on:
      - mssql
      - redis
    networks:
      - sme-network
    volumes:
      - ./backend/logs:/app/logs

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sme-dashboard-frontend
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
      - REACT_APP_SOCKET_URL=http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - sme-network

volumes:
  mssql_data:
  redis_data:


networks:
  sme-network:
    driver: bridge
